// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'app.dart';

List<RouteEntity> get routes => [
  RouteEntity(key: '/', uri: Uri.parse('/'), routeBuilder: b0Builder),
  RouteEntity(key: '/info', uri: Uri.parse('/info'), routeBuilder: b1Builder),
  RouteEntity(
    key: '/ptd/stocks/[id]',
    parent: '/ptd',
    uri: Uri.parse('/ptd/stocks/[id]'),
    routeBuilder: b2Builder,
  ),
  RouteEntity(
    key: '/ptd/stocks',
    parent: '/ptd',
    uri: Uri.parse('/ptd/stocks'),
    routeBuilder: b3Builder,
  ),
  RouteEntity(
    key: '/ptd/option2',
    parent: '/ptd',
    uri: Uri.parse('/ptd/option2'),
    routeBuilder: b4Builder,
  ),
  RouteEntity(
    key: '/ptd/option3',
    parent: '/ptd',
    uri: Uri.parse('/ptd/option3'),
    routeBuilder: b5Builder,
  ),
  RouteEntity(key: '/ptd', uri: Uri.parse('/ptd'), routeBuilder: b6Builder),
  RouteEntity(
    key: '/auth/signup',
    uri: Uri.parse('/auth/signup'),
    routeBuilder: b7Builder,
  ),
  RouteEntity(
    key: '/auth/signin',
    uri: Uri.parse('/auth/signin'),
    routeBuilder: b8Builder,
  ),
  RouteEntity(
    key: '/auth/forgot_password',
    uri: Uri.parse('/auth/forgot_password'),
    routeBuilder: b9Builder,
  ),
];

const routePaths = (
  path: '/',
  info: '/info',
  ptd: (
    path: '/ptd',
    stocks: (path: '/ptd/stocks', $id: '/ptd/stocks/[id]'),
    option2: '/ptd/option2',
    option3: '/ptd/option3',
  ),
  auth: (
    path: '/auth',
    signup: '/auth/signup',
    signin: '/auth/signin',
    forgotPassword: '/auth/forgot_password',
  ),
);
