// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

import 'package:flutter/widgets.dart';
import 'package:routefly/routefly.dart';

import 'app/app_page.dart' as a0;
import 'app/auth/forgot_password_page.dart' as a9;
import 'app/auth/signin_page.dart' as a8;
import 'app/auth/signup_page.dart' as a7;
import 'app/info/info_page.dart' as a1;
import 'app/ptd/option2_page.dart' as a4;
import 'app/ptd/option3_page.dart' as a5;
import 'app/ptd/ptd_layout.dart' as a6;
import 'app/ptd/stocks/[id]_page.dart' as a2;
import 'app/ptd/stocks/stocks_page.dart' as a3;

Route b0Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a0.AppPage());
Route b1Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a1.InfoPage());
Route b2Builder(BuildContext context, RouteSettings settings) =>
    a2.routeBuilder(context, settings);
Route b3Builder(BuildContext context, RouteSettings settings) =>
    a3.routeBuilder(context, settings);
Route b4Builder(BuildContext context, RouteSettings settings) =>
    a4.routeBuilder(context, settings);
Route b5Builder(BuildContext context, RouteSettings settings) =>
    a5.routeBuilder(context, settings);
Route b6Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a6.PtdLayout());
Route b7Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a7.SignUpPage());
Route b8Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a8.SigninPage());
Route b9Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a9.ForgotPasswordPage());
