// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1fNpPUtNKhJcAb1P7WUTYLZ7NMij_uOg',
    appId: '1:853038746887:web:7d6c35c7abcff0c85509a2',
    messagingSenderId: '853038746887',
    projectId: 'hubapp-2cb33',
    authDomain: 'hubapp-2cb33.firebaseapp.com',
    storageBucket: 'hubapp-2cb33.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgF7EGfs5KmKYkpLvzLEQOtltxgfUJOAg',
    appId: '1:853038746887:android:1f68d6af578edaf45509a2',
    messagingSenderId: '853038746887',
    projectId: 'hubapp-2cb33',
    storageBucket: 'hubapp-2cb33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPwC-sGmcmeGhugiywidgSFi9usKcmGHo',
    appId: '1:853038746887:ios:1e37501463598a3a5509a2',
    messagingSenderId: '853038746887',
    projectId: 'hubapp-2cb33',
    storageBucket: 'hubapp-2cb33.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
