// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'my_app.dart';

List<RouteEntity> get routes => [
  RouteEntity(key: '/', uri: Uri.parse('/'), routeBuilder: b0Builder),
  RouteEntity(
    key: '/products/[id]/product',
    uri: Uri.parse('/products/[id]/product'),
    routeBuilder: b1Builder,
  ),
  RouteEntity(
    key: '/products',
    uri: Uri.parse('/products'),
    routeBuilder: b2Builder,
  ),
];

const routePaths = (
  path: '/',
  products: (
    path: '/products',
    $id: (path: '/products/[id]', product: '/products/[id]/product'),
  ),
);
