version: "3.8"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rotarydb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    secrets:
      - postgres-password

  api:
    image: ghcr.io/wesleydev184/rotary:main
    restart: always
    environment:
      DB_URL: "Host=db;Port=5432;Database=rotarydb;Username=postgres;Password=postgres"
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres-data:
