apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
        - name: registry-auth-container
      containers:
        - name: api
          image: registry.hubsolidario.com/hubs/api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          envFrom:
            - secretRef:
                name: api-env-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 5
      initContainers:
        - name: wait-for-db
          image: postgres:15
          command:
            - sh
            - -c
            - |
              until pg_isready -h db -p 5432 -U postgres; do
                echo "Waiting for database...."
                sleep 2
              done
              echo "Database is ready!"
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - port: 5001
      targetPort: 5001
  type: ClusterIP
