# --- API IngressRoute ---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: api-ingressroute
  namespace: core
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - match: Host(`api.core.hubsolidario.com`)
      kind: Rule
      services:
        - name: api
          port: 5001
  tls:
    certResolver: letsencrypt
---
# --- MinIO API IngressRoute ---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio-api-ingressroute
  namespace: core
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - match: Host(`s3.core.hubsolidario.com`)
      kind: Rule
      services:
        - name: minio-api
          port: 9000
  tls:
    certResolver: letsencrypt
---
# --- MinIO Console IngressRoute ---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio-console-ingressroute
  namespace: core
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - match: Host(`minio-console.core.hubsolidario.com`)
      kind: Rule
      services:
        - name: minio-console
          port: 9001
  tls:
    certResolver: letsencrypt
---
# --- Harbor Registry IngressRoute (Docker API) ---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: harbor-registry-ingressroute
  namespace: harbor
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - match: Host(`registry.core.hubsolidario.com`)
      kind: Rule
      services:
        - name: harbor-registry
          port: 5000
  tls:
    certResolver: letsencrypt
---
# --- Harbor Portal IngressRoute (Web UI) ---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: harbor-portal-ingressroute
  namespace: harbor
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - match: Host(`harbor.core.hubsolidario.com`)
      kind: Rule
      services:
        - name: harbor-portal
          port: 8080
  tls:
    certResolver: letsencrypt
---
# --- Harbor Core API IngressRoute ---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: harbor-core-ingressroute
  namespace: harbor
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - match: Host(`harbor-api.core.hubsolidario.com`)
      kind: Rule
      services:
        - name: harbor-core
          port: 8080
  tls:
    certResolver: letsencrypt
