apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
        - name: n8n
          image: n8nio/n8n:latest
          ports:
            - containerPort: 5678
          env:
            - name: WEBHOOK_URL
              value: "http://n8n:5678"
            - name: N8N_HOST
              value: "0.0.0.0"
            - name: GENERIC_TIMEZONE
              value: "America/Sao_Paulo"
            - name: N8N_LOG_LEVEL
              value: "debug"
            - name: N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE
              value: "true"
          volumeMounts:
            - name: n8n-data
              mountPath: /home/node/.n8n
      volumes:
        - name: n8n-data
          persistentVolumeClaim:
            claimName: n8n-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: n8n
  namespace: core
spec:
  selector:
    app: n8n
  ports:
    - port: 5678
      targetPort: 5678
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data-pvc
  namespace: core
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
